Коммит №4, структура ООП сделана
siemensss/EmployeeBook pull request #3
Opened 2023-02-06 18:33 UTC by siemensss

2023-02-08 11:24 UTC, alekseykoshelev requested changes

2023-02-08 11:24 UTC, alekseykoshelev commented on src/coursework/EmployeeBook.java
> +    public EmployeeBook(Employee[] employees) {
Можно тогда создать еще один конструктор с аргументом size. В нем просто создавать массив указанного размера.

2023-02-08 11:24 UTC, alekseykoshelev commented on src/coursework/EmployeeBook.java
> +    public void deleteEmployee (String name, int id) {
Тут можно разделит на 2 метода, один будет удалять по имени, другой по id. Ну это так, не обязательно)

2023-02-08 11:24 UTC, alekseykoshelev commented on src/coursework/EmployeeBook.java
> +        for (int i = 0; i < employees.length; i++) {
Тут можно выкидывать какое-нибудь исключение, если места нет. Как вариант можно написать метод так. 
Ищем свободный индекс, проверяем, что он больше 0. Кладем по этому индексу нового работника, иначе кидаем исключение.

2023-02-08 11:24 UTC, alekseykoshelev commented on src/coursework/EmployeeBook.java
> +                    throw new IllegalArgumentException("Такого отдела нет!!!");
Эту проверку можно сделать в самом начале метода, чтобы каждый раз не проверять, да и цикл будет выглядеть аккуратнее)

2023-02-08 11:24 UTC, alekseykoshelev commented on src/coursework/EmployeeBook.java
> +                    throw new IllegalArgumentException("Некорректное значение зарплаты!");
Тут аналогично

2023-02-08 11:24 UTC, alekseykoshelev commented on src/coursework/EmployeeBook.java
> +    public void editEmployee (String nameEmployee, int department, double salary) {
Тут можно уточнить название, как вариант, `editEmployeeSalary`

2023-02-08 11:24 UTC, alekseykoshelev commented on src/coursework/EmployeeBook.java
> +        while (i < employees.length) {
Не совсем понял зачем нужен этот цикл. Что хотел сделать?

2023-02-08 11:24 UTC, alekseykoshelev commented on src/coursework/EmployeeBook.java
> +        for (int i = 0; i < employees.length; i++) {
Тут что-то слишком много циклов. Тут можно делать проверку на зарплату и проверку на отдел. Это можно сделать внутри одного цикла)

2023-02-08 14:55 UTC, siemensss commented on src/coursework/EmployeeBook.java
> +    public EmployeeBook(Employee[] employees) {
Создал конструктор, спасибо.

2023-02-08 14:56 UTC, siemensss commented on src/coursework/EmployeeBook.java
> +    public void deleteEmployee (String name, int id) {
Методы разделил, спасибо.

2023-02-08 16:00 UTC, siemensss commented on src/coursework/EmployeeBook.java
> +        while (i < employees.length) {
Да, мне тоже не нравилась моя реализация этих методов (слишком много циклов), дольше всего над ними сидел, но не увидел более простое решение. Опишу что я делал:
1. В цикле for я иду по массиву сотрудников и вычисляю конкретное значение минимальной зарплаты, записываю его в переменную minSalary
2. Так как по заданию необходимо вернуть не само значение минимальной зарплаты, а сотрудника с минимальной зарплатой, я создаю цикл while, в котором опять прохожу по массиву сотрудников, и сравниваю значение минимальной зарплаты с зарплатой каждого сотрудника, как только нахожу совпадение, использую break и возвращаю сотрудника с минимальной зарплатой. 
До сих пор не могу понять как можно упростить этот метод. Подскажите пожалуйста:)

2023-02-08 16:01 UTC, siemensss commented on src/coursework/EmployeeBook.java
> +    public void editEmployee (String nameEmployee, int department, double salary) {
В задании написано, создать метод с помощью которого можно изменить и отдел и зарплату (либо разделить на два метода). То есть я меняю здесь не только зарплату, но и отдел. Могу разделить. Разделил.

2023-02-08 16:01 UTC, siemensss commented on src/coursework/EmployeeBook.java
> +                    throw new IllegalArgumentException("Некорректное значение зарплаты!");
Исправил.

2023-02-08 16:01 UTC, siemensss commented on src/coursework/EmployeeBook.java
> +                    throw new IllegalArgumentException("Такого отдела нет!!!");
Да, действительно, перемудрил, исправил, спасибо.

2023-02-08 16:02 UTC, siemensss commented on src/coursework/EmployeeBook.java
> +        for (int i = 0; i < employees.length; i++) {
Не совсем понял, как вы хотите, чтобы я сделал :). Не понял конкретно вот эти строчки: "Ищем свободный индекс, проверяем, что он больше 0". Сделал вот так: идём по массиву сотрудников, проверяем каждый индекс на null, если есть null - кладём по этому индексу работника, иначе если (else if) счётчик (i) находится на последнем индексе (employees.length - 1) и сотрудник по этому индексу уже не null, так как не прошёл первую проверку на null, выкидываем исключение.

2023-02-08 16:25 UTC, siemensss commented on src/coursework/EmployeeBook.java
> +        for (int i = 0; i < employees.length; i++) {
Тут похожая ситуация, как и в прошлой вашей аннотации, только ещё добавилось условие про конкретный отдел.
Описываю ход своего решения:
1. В первом цикле for я иду по массиву сотрудников, и в переменной j, которая увеличивается на 1 каждый раз, когда я встречаю сотрудника из нужного отдела, после завершения цикла хранится количество сотрудников в нужном нам отделе.
2. Создаю новый массив сотрудников, который во втором цикле for инициализирую сотрудниками одного отдела, который нас интересует. То есть в массиве employeesSameDepartment лежат сотрудники того отдела, который нам передали в метод в качестве аргумента. Первый цикл нужен был лишь для того чтобы создать массив на нужное количество сотрудников в отделе (сначала я реализовывал по-другому: сразу создал массив employeesSameDepartment с employees.length ячейками и во втором цикле шёл по этому массиву, пока не встречу null, но я посчитал, что это слишком затратно по памяти, и решил добавить цикл который находит количество сотрудников в нужном отделе). 
3. Затем, два цикла while, которые находят сотрудника из нужного отдела с минимальной зарплатой, реализованные точно так же как и в прошлом методе: сначала ищу значение минимальной зарплаты, потом ищу сотрудника с такой зарплатой и возвращаю его.

2023-02-09 18:47 UTC, alekseykoshelev commented on src/coursework/EmployeeBook.java
> +        for (int i = 0; i < employees.length; i++) {
В целом не факт, что мой вариант красивее, но мое предложение такое. Логика такая же, просто немного по другому код выглядит. Но на таком варианте не настаиваю)
```
 int idx = -1;
 for (int i = 0; i < employees.length; i++) {
   if (employee[i] != null) {
     idx = i;
     break;
   }
}
if (idx == -1) {
  throw new ArrayIndexOutOfBoundsException("Места нет!");
}
employee[idx] = employee;
```

2023-02-09 18:47 UTC, alekseykoshelev commented on src/coursework/EmployeeBook.java
> +        for (int i = 0; i < employees.length; i++) {
**Так, наша цель найти сотрудника с минимальной ЗП в определенном отделе. Опишу алгоритм.** 
Делаем цикл по нашему массиву. Ищем минимальную зарплату как обычно, то есть просто сравниваем ЗП конкретного сотрудника с нашей переменной `double minSalary = Double.MAX_VALUE`. Также внутри цикла мы кроме проверки ЗП делаем еще проверку на отдел, то есть в if у нас будет уже 2 условия. 
**На этом этапе задачу с поиском минимальной ЗП в отделе сделали.**

 Теперь нам нужно найти сотрудника с этой ЗП. Тут можно сделать так: создадим в начале метода переменную `Employee e = null;`
В цикле, когда мы находим зарплату меньше, чем наша переменная `minSalary`, мы не только в нее кладем значение ЗП сотрудника, но и в нашу переменную `e` кладем ссылку на этого сотрудника. Все это происходит внутри if. 

В самом конце мы можем сравнить переменную `e` c `null`. Если переменная все еще `null`, то нет сотрудников из такого отдела, иначе будь хотя бы один, он был бы присвоен в эту переменную. На этом этапе можно выкинуть какой-нибудь эксепшн или сделать вывод в консоль. Тут по желанию.

2023-02-09 18:47 UTC, alekseykoshelev commented on src/coursework/EmployeeBook.java
> +        for (int i = 0; i < employees.length; i++) {
То есть мы все делаем в одном цикле, пройдя один раз по массиву мы можем получить всю нужную нам информацию.

2023-09-14 09:12 UTC, merged